#!/usr/bin/env python3
"""Generate src/formats/MetadataTables.cpp from data/metadata.json.

data/metadata.json is written by tools/metadata-export (a .NET tool that reads
the tables out of the C# build), so the paths are resolved by the C# code:
    dotnet run --project tools/metadata-export -c Release -- data/metadata.json
"""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / "data/metadata.json").read_text(encoding="utf-8"))
out = root / "src/formats/MetadataTables.cpp"


def s(v):
    return "nullptr" if not v else json.dumps(v)


def ints(values):
    return "{" + ", ".join(str(int(v)) for v in values) + "}"


def f(x):
    r = "%.9g" % x
    return (r if any(c in r for c in ".e") else r + ".0") + "f"


lines = [
    "// Generated by tools/gen_metadata.py from data/metadata.json. Do not edit.",
    '#include "Metadata.h"',
    "",
    "namespace fp {",
    "",
    "const std::vector<ModelMetadata>& modelTable()",
    "{",
    "    static const std::vector<ModelMetadata> table = {",
]
for name, m in data["models"].items():
    recolors = []
    for r in m["recolors"]:
        replace = ", ".join("{%d, %s}" % (e["from"], ints(e["to"])) for e in r["replaceIds"])
        recolors.append("{%s, %s, %s, %s, %s, {%s}}" % (
            s(r["name"]), s(r["modelPath"]), s(r["texturePath"]), s(r["palettePath"]), s(r["replacePath"]), replace))
    lines.append("        {%s, %s, %s, %s, {%s}}," % (
        s(name), s(m["modelPath"]), s(m["animationPath"]), s(m["animationShare"]), ", ".join(recolors)))
lines += ["    };", "    return table;", "}", ""]

lines += ["const std::vector<DoorMetadata>& doorTable()", "{", "    static const std::vector<DoorMetadata> table = {"]
for d in data["doors"]:
    lines.append("        {%s, %s, %s, %s}," % (s(d["name"]), s(d["lockName"]), f(d["lockOffset"]), f(d["radius"])))
lines += ["    };", "    return table;", "}", ""]

lines += ["const std::vector<int>& doorPaletteTable()", "{",
          "    static const std::vector<int> table = %s;" % ints(data["doorPalettes"]), "    return table;", "}", ""]

for fn, key in (("jumpPadTable", "jumpPads"), ("itemTable", "items")):
    lines += ["const std::vector<const char*>& %s()" % fn, "{",
              "    static const std::vector<const char*> table = {%s};" % ", ".join(s(n) for n in data[key]),
              "    return table;", "}", ""]

lines += ["const std::vector<ObjectMetadata>& objectTable()", "{", "    static const std::vector<ObjectMetadata> table = {"]
for o in data["objects"]:
    v = o["visPosOffset"]
    lines.append("        {%s, %s, %d, %s, {%s, %s, %s}}," % (
        s(o["name"]), "true" if o["lighting"] else "false", o["recolorId"], ints(o["animationIds"]), f(v[0]), f(v[1]), f(v[2])))
lines += ["    };", "    return table;", "}", ""]

lines += ["const std::vector<PlatformMetadata>& platformTable()", "{", "    static const std::vector<PlatformMetadata> table = {"]
for p in data["platforms"]:
    if p is None:
        lines.append("        {nullptr, false, {-1, -1, -1, -1}},")
    else:
        lines.append("        {%s, %s, %s}," % (s(p["name"]), "true" if p["lighting"] else "false", ints(p["animationIds"])))
lines += ["    };", "    return table;", "}", ""]

pv = data["playerValues"]
fields = [k for k in pv[0].keys()]
lines += ["const std::vector<PlayerValues>& playerValuesTable()", "{", "    static const std::vector<PlayerValues> table = {"]
for v in pv:
    lines.append("        {" + ", ".join(str(int(v[k])) for k in fields) + "},")
lines += ["    };", "    return table;", "}", ""]
lines += ["const std::array<float, 4>& slipSpeedFactors()", "{",
          "    static const std::array<float, 4> t = {%s};" % ", ".join(f(x) for x in data["slipSpeedFactors"]), "    return t;", "}", ""]
lines += ["const std::array<float, 4>& tractionFactors()", "{",
          "    static const std::array<float, 4> t = {%s};" % ", ".join(f(x) for x in data["tractionFactors"]), "    return t;", "}", ""]
# WeaponInfo: every numeric property of the C# WeaponInfo, camelCased, raw
# values (fixed point stays fixed point); two-element arrays stay arrays, a
# ricochet weapon is an index into ricochetWeapons() or -1.
weapon_fields = [k for k, v in data["weaponsMP"][0].items() if k not in ("Name", "Description")]


def camel(k):
    return k[0].lower() + k[1:]


def weapon_row(w):
    values = [s(w["Description"])]
    for k in weapon_fields:
        v = w[k]
        values.append(ints(v) if isinstance(v, list) else str(int(v)))
    return "        {" + ", ".join(values) + "},"


for fn, key in (("weaponsMP", "weaponsMP"), ("ricochetWeapons", "ricochetWeapons")):
    lines += ["const std::vector<WeaponInfo>& %s()" % fn, "{", "    static const std::vector<WeaponInfo> table = {"]
    lines += [weapon_row(w) for w in data[key]]
    lines += ["    };", "    return table;", "}", ""]
lines += ["const std::vector<EffectMetadata>& effectTable()", "{", "    static const std::vector<EffectMetadata> table = {"]
for e in data["effects"]:
    lines.append("        {%s, %s}," % (json.dumps(e["name"]), s(e["archive"])))
lines += ["    };", "    return table;", "}", ""]
lines += ["const std::vector<int>& syluxBombEffects()", "{",
          "    static const std::vector<int> table = %s;" % ints(data["syluxBombEffects"]), "    return table;", "}", ""]

lines += ["const std::vector<int>& beamDrawEffects()", "{",
          "    static const std::vector<int> table = %s;" % ints(data["beamDrawEffects"]), "    return table;", "}", ""]
lines += ["const std::vector<int>& affinityWeapons()", "{",
          "    static const std::vector<int> table = %s;" % ints(data["affinityWeapons"]), "    return table;", "}", ""]
lines += ["const std::vector<int>& gunAnimationIds()", "{",
          "    static const std::vector<int> table = %s;" % ints(data["gunAnimationIds"]), "    return table;", "}", ""]

hud = data["hud"]


def hud_struct(name, rows):
    keys = list(rows[0].keys())
    decl = []
    for k in keys:
        v = rows[0][k]
        decl.append("    %s %s;" % ("const char*" if isinstance(v, str) or v is None else "bool" if isinstance(v, bool) else "int32_t", k))
    body = []
    for r in rows:
        vals = []
        for k in keys:
            v = r[k]
            vals.append(s(v) if isinstance(v, str) or v is None else ("true" if v else "false") if isinstance(v, bool) else str(int(v)))
        body.append("        {" + ", ".join(vals) + "},")
    return decl, body


hud_decls = []
for struct, fn, key in (("HudHunterObjects", "hudHunterObjects", "hunterObjects"), ("HudMeterInfo", "hudMainHealthbars", "mainHealthbars"),
                        ("HudMeterInfo", "hudSubHealthbars", "subHealthbars"), ("HudMeterInfo", "hudAmmoBars", "ammoBars")):
    decl, body = hud_struct(struct, hud[key])
    if struct not in [d[0] for d in hud_decls]:
        hud_decls.append((struct, decl))
    lines += ["const std::vector<%s>& %s()" % (struct, fn), "{", "    static const std::vector<%s> table = {" % struct] + body
    lines += ["    };", "    return table;", "}", ""]
lines += ['const char* hudBoostFile() { return %s; }' % s(hud["boost"]), 'const char* hudBombsFile() { return %s; }' % s(hud["bombs"]), ""]
lines += ["} // namespace fp", ""]

(root / "src/formats/HudStructs.inc").write_text("// Generated by tools/gen_metadata.py from HUD/HudInfo.cs (HudObjects, HudMeter).\n"
    + "\n".join("struct %s {\n%s\n};" % (n, "\n".join(d)) for n, d in hud_decls) + "\n", encoding="utf-8")

header = root / "src/formats/PlayerValues.inc"
header.write_text("// Generated by tools/gen_metadata.py. Fields of PlayerValues (Entities/Players/PlayerEntity.cs), raw values.\n"
    + "\n".join("    int32_t %s;" % k for k in fields) + "\n", encoding="utf-8")

(root / "src/formats/WeaponInfo.inc").write_text(
    "// Generated by tools/gen_metadata.py. Fields of WeaponInfo (Metadata/Weapons.cs), raw values.\n    const char* name;\n"
    + "\n".join("    %s %s;" % ("std::array<int32_t, 2>" if isinstance(data["weaponsMP"][0][k], list) else "int32_t", camel(k))
                for k in weapon_fields) + "\n", encoding="utf-8")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"{len(data['models'])} models -> {out.relative_to(root)}", file=sys.stderr)
