#!/usr/bin/env python3
"""Generate src/formats/RoomTable.inc from src/MphRead/Metadata/Rooms.cs."""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
src = (root / "src/MphRead/Metadata/Rooms.cs").read_text(encoding="utf-8")
out = root / "cpp/src/formats/RoomTable.inc"


def split_args(body):
    args, depth, cur, quoted = [], 0, "", False
    for ch in body:
        if ch == '"':
            quoted = not quoted
        if quoted:
            cur += ch
            continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            args.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        args.append(cur.strip())
    return dict(a.split(":", 1) for a in args if ":" in a)


def extract_calls(text):
    i = 0
    while True:
        i = text.find("new RoomMetadata(", i)
        if i < 0:
            return
        j = i + len("new RoomMetadata(")
        depth = 1
        k = j
        while depth:
            if text[k] == "(":
                depth += 1
            elif text[k] == ")":
                depth -= 1
            k += 1
        yield text[j:k - 1]
        i = k


def s(v):
    v = v.strip()
    return "nullptr" if v == "null" else v


def color(v):
    m = re.match(r"new ColorRgb\((\d+),\s*(\d+),\s*(\d+)\)", v.strip())
    return "{%s, %s, %s}" % m.groups()


def flt(x):
    r = "%.9g" % x
    return (r if any(c in r for c in ".e") else r + ".0") + "f"


def vec(v):
    v = v.strip()
    m = re.match(r"new Vector3Fx\((-?\d+),\s*(-?\d+),\s*(-?\d+)\)", v)
    if m:
        return "{%s}" % ", ".join(flt(int(x) / 4096) for x in m.groups())
    m = re.match(r"new Vector3\((-?[\d.]+)f?,\s*(-?[\d.]+)f?,\s*(-?[\d.]+)f?\)", v)
    if m:
        return "{%s}" % ", ".join(flt(float(x)) for x in m.groups())
    raise ValueError(v)


def b(d, k):
    return "true" if d.get(k, "false").strip() == "true" else "false"


src = re.sub(r"//[^\n]*", "", src)
rows = []
for body in extract_calls(src):
    d = split_args(body)
    zero = "{0.0f, 0.0f, 0.0f}"
    limits = {k: vec(d[k]) if k in d else zero for k in ("cameraMin", "cameraMax", "playerMin", "playerMax")}
    has_limits = any(v != zero for v in limits.values())
    rows.append(
        "    {%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s},"
        % (
            d["id"].strip(), s(d["name"]), s(d["inGameName"]), s(d["archive"]),
            s(d["modelPath"]), s(d["animationPath"]), s(d["collisionPath"]), s(d["texturePath"]), s(d["entityPath"]), d["nodeLayer"].strip(),
            b(d, "fogEnabled"), color(d["fogColor"]), d["fogSlope"].strip(), d["fogOffset"].strip(),
            color(d["light1Color"]), vec(d["light1Vector"]),
            color(d["light2Color"]), vec(d["light2Vector"]),
            b(d, "multiplayer"), b(d, "firstHunt"), b(d, "hybrid"),
            flt(int(d["killHeight"].strip()) / 4096), limits["playerMin"], limits["playerMax"], "true" if has_limits else "false",
            s(d.get("nodePath", "null")),
        )
    )

out.write_text(
    "// Generated by tools/gen_rooms.py from src/MphRead/Metadata/Rooms.cs. Do not edit.\n"
    + "\n".join(rows) + "\n",
    encoding="utf-8",
)
print(f"{len(rows)} rooms -> {out.relative_to(root)}", file=sys.stderr)
