#!/usr/bin/env python3
"""Generate src/audio/SequencerTables.inc from the NcsfPlay sources (src/NcsfPlay).

The DS sound driver's lookup tables: volume, pitch, sustain and scale.
"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
NCSF = HERE.parent.parent / "src/NcsfPlay"
TARGET = HERE.parent / "src/audio/SequencerTables.inc"


def table(path, name):
    text = (NCSF / path).read_text(encoding="utf-8")
    match = re.search(name + r"\s*=\s*\[(.*?)\];", text, re.S)
    if not match:
        raise SystemExit(f"{name} not found in {path}")
    values = [v.strip() for v in match.group(1).replace("\n", " ").split(",") if v.strip()]
    return values


out = ["// Generated by tools/gen_sseq_tables.py from src/NcsfPlay. Do not edit.", ""]
for ctype, path, name, cname in (
    ("uint8_t", "Channel.cs", "GetVolumeTable", "kVolumeTable"),
    ("uint16_t", "Channel.cs", "GetPitchTable", "kPitchTable"),
    ("int16_t", "Channel.cs", "convertSustainLookupTable", "kSustainTable"),
    ("int16_t", "NCSF.cs", "convertScaleLookupTable", "kScaleTable"),
    ("uint8_t", "Channel.cs", "AttackCoefficientTable", "kAttackTable"),
):
    values = table(path, name)
    out.append(f"constexpr {ctype} {cname}[{len(values)}] = {{")
    for i in range(0, len(values), 16):
        out.append("    " + ", ".join(values[i:i + 16]) + ",")
    out.append("};")
    out.append("")
TARGET.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {TARGET}")
