#!/usr/bin/env python3
"""Generate src/audio/SoundIds.h from src/MphRead/Metadata/SoundMeta.cs.

The C# enums SfxId, SeqId, MusicId and VoiceId become C++ enums of the same
names and values (SfxId keeps its 0x4000 script / 0x8000 DGN flag bits).
"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE.parent.parent / "src/MphRead/Metadata/SoundMeta.cs"
TARGET = HERE.parent / "src/audio/SoundIds.h"

text = SOURCE.read_text(encoding="utf-8")
out = [
    "#pragma once",
    "",
    "// Generated by tools/gen_sound_ids.py from src/MphRead/Metadata/SoundMeta.cs. Do not edit.",
    "namespace fp {",
    "",
]
for name in ("HunterSfx", "BeamSfx", "TerrainSfx", "VoiceId", "SeqId", "MusicId", "SfxId"):
    match = re.search(r"public enum " + name + r"\s*\{(.*?)\n    \}", text, re.S)
    if not match:
        raise SystemExit(f"enum {name} not found")
    out.append(f"enum class {name} : int {{")
    for line in match.group(1).splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line:
            continue
        key, value = (part.strip() for part in line.split("="))
        out.append(f"    {key} = {value},")
    out.append("};")
    out.append("")
out.append("} // namespace fp")
TARGET.parent.mkdir(parents=True, exist_ok=True)
TARGET.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {TARGET}")
