<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>nettest</AssemblyName>
    <RootNamespace>MphRead.NetTest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/MphRead/Mods/Network/NetProtocol.cs" />
    <Compile Include="../../src/MphRead/Mods/Network/NetTransport.cs" />
    <Compile Include="../../src/MphRead/Mods/Network/NetProbe.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
  </ItemGroup>
</Project>
